version: '3.9'
services:
  flask_web:
    container_name: flask_web_container
    build: .
    ports:
      - 8000:8000
    restart: unless-stopped
    networks:
      default:
        ipv4_address: 94.198.218.2